language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: share-your-ideas-api
  api_key:
    secure: RH2T3dLpOTEODIMmp3de+WUjNpa/KGBFDik+KzywOyujKgdLE5VE5GfiULzUBoOek/eVncem0duf+v0axPY40LXmnWH0Xz+UckQO8MSQwdc8iJTGy1tvxikxCePOAxM5G92Keo0yOKItpN19NlkmLVC96tk9ZRjWdabn2TjeGxP8u6eGO+wB3v0mXea2yQlvrsxtbqKW4fQ45w5uzSk7vw6DvOSBWv2zlunbWBU1JLTr+Q1SNgR4bgUWU+Cs824McberJUE24KIPLXHx/BMda/4dM5xMoY+Goh+rkkiCJATthwzfIVGuOSspjTmGLr8XSppfoxKtfZGAJhyQLE2/GlVIWePMV4lY73nyrx3u/Wi+kp/7wjtqChyEkk9i1VAa8rzEiUyW5pAo6mS8PAGf+xjOOo3Vmy8aOX1YkHusLBz5OFZnYYZDVwtsu1hThIMjXNluQbajOUm0rkImQGgtilCZUa23JeTs4GTG01k7X1xcItJUGdf8X+Dedxps+BRAplv5vGL+9ArOyqgnfIlDSWOEN+Qwg2TRBo5jQuVT6lPDcw5oObVCDq4zSoZYTHmscj+KMjWwCXowMYpSXjyfpJZWPQktaACiDFPG4EpoJtHEmhSGZ2joY0M1tkP34KHHg3LUXB1KDpJH7rzZfRjegJFggKQvA4sjx5FKw8N76hU=
