version: "3"
services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/test
      - APP_NAME=Share Your Ideas
      - JWT_SECRET=123456789
      - CACHE_KEY=987654321
      - SWAGGER_DOC=swaggerPROD
    ports:
      - "5000:5000"
  mongo:
    image: mongo
